# Generated by Django 4.2.4 on 2024-02-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=1000, verbose_name='Titulo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('description', models.TextField(null=True, verbose_name='Descripción')),
            ],
        ),
    ]
